/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/overview/reply/Comment.vue')['default']
    Comments: typeof import('./src/components/overview/reply/Comments.vue')['default']
    Datas: typeof import('./src/components/overview/Datas.vue')['default']
    Doughnut: typeof import('./src/components/echarts/Doughnut.vue')['default']
    DoughnutChart: typeof import('./src/components/echarts/DoughnutChart.vue')['default']
    Gather: typeof import('./src/components/overview/Gather.vue')['default']
    HeadBar: typeof import('./src/components/bar/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAlarmFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconAlarmFill']
    IconBellOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconBellOutline']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    IconYike1Outline: typeof import('@yike-design/ui/es/components/svg-icon')['IconYike1Outline']
    Line: typeof import('./src/components/echarts/Line.vue')['default']
    LineChart: typeof import('./src/components/echarts/LineChart.vue')['default']
    Menu: typeof import('./src/components/bar/Menu.vue')['default']
    MenuBar: typeof import('./src/components/bar/MenuBar.vue')['default']
    Reply: typeof import('./src/components/overview/reply/Reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopTitle: typeof import('./src/components/bar/TopTitle.vue')['default']
    YkAvatar: typeof import('@yike-design/ui/es')['YkAvatar']
    YkButton: typeof import('@yike-design/ui/es')['YkButton']
    YkInput: typeof import('@yike-design/ui/es')['YkInput']
    YkRadio: typeof import('@yike-design/ui/es')['YkRadio']
    YkRadioGroup: typeof import('@yike-design/ui/es')['YkRadioGroup']
    YkSpace: typeof import('@yike-design/ui/es')['YkSpace']
    YkText: typeof import('@yike-design/ui/es')['YkText']
    YkTheme: typeof import('@yike-design/ui/es')['YkTheme']
    YkTitle: typeof import('@yike-design/ui/es')['YkTitle']
  }
}
